# Generated by Django 5.0.2 on 2024-02-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('tags', models.CharField(blank=True, max_length=800, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
