# Generated by Django 5.0.2 on 2024-02-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_remove_item_quantity_item_availble_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='reporter',
            new_name='category',
        ),
    ]
